--2. Выберите имя пассажира, аэропорт отправления, 
--статус рейса, а также класс обслуживания и стоимость у перелета, где id пассажира начинается с "5657". 

--SELECT TICKETS.PASSENGER_NAME, FLIGHTS.DEPARTURE_AIRPORT, FLIGHTS.STATUS, TICKET_FLIGHTS.FARE_CONDITIONS, TICKET_FLIGHTS.AMOUNT
--FROM TICKETS
--JOIN TICKET_FLIGHTS ON TICKET_FLIGHTS.TICKET_NO = TICKETS.TICKET_NO 
--JOIN FLIGHTS ON FLIGHTS.FLIGHT_ID = TICKET_FLIGHTS.FLIGHT_ID
--WHERE LEFT(TICKETS.PASSENGER_ID, 4)  LIKE '5657';	

--3. Выберите все модели самолетов, у которых количество мест бизнес класса больше 20.
--SELECT AIRCRAFTS_DATA.AIRCRAFT_CODE, AIRCRAFTS_DATA.MODEL,
--COUNT(S.FARE_CONDITIONS)
--FROM AIRCRAFTS_DATA
--LEFT JOIN SEATS S ON AIRCRAFTS_DATA.AIRCRAFT_CODE = S.AIRCRAFT_CODE
--GROUP BY AIRCRAFTS_DATA.AIRCRAFT_CODE
--HAVING COUNT(S.FARE_CONDITIONS) > 20;
